### ISSUE TITLE
Problemas con el sistema de roles

### ISSUE THREAD

**Issue by jesusr00** [Streaming-Cuba/events-backend#7]
En el endpont https://api.eventos.streamingcuba.com/api/v1/auth/me devuelves lo roles como un aareglo de string con los nosmbres de los roles en vez de un arreglo de int con los id de los roles mientras que en el endpint https://api.eventos.streamingcuba.com/api/v1/account/{id} devuelves un arreglo vacío

**Comment by jorgeajimenezl** [comment]
Ya se arreglo para api/v1/account/{id} devuelva bien, solo falta mergear los cambios
